# default configuration
baseURL = "https://rodosingh.netlify.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Rodo"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "projects"
name = "Projects"
weight = 2

[[menu.main]]
URL = "gallery"
name = "Gallery"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = "images/favicon_rodo.png"
#cv-URL
cv_url = "https://drive.google.com/file/d/1ZA6Yhob0kGXXqO-JJoKVWMl6j6fM-uUN/view?usp=sharing"
# theme color
theme_color = "#001a33"
# contact info
icon = "ti-mobile"
phone = "+91 9777 507 538"
email = "adityasinghdrdo@gmail.com"
address = "IIIT Hyderabad, Gachibowli-Area, Hyderabad, India"
# meta description
author = "Aditya Kumar Singh"
description = "A Data Fanatic"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2022 | Made with &hearts; by [rodosingh](https://www.linkedin.com/in/aditya-singh-9639a8175/) | Powered by [Hugo](https://gohugo.io/) | Published by [Netlify](https://www.netlify.com/)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "https://formspree.io/f/myylboak" # contact form works with : https://formspree.io

# google map
[params.map]
enable = true
gmap_api = "https://maps.google.com/maps?q=IIIT%20Hyderabad&t=&z=17&ie=UTF8&iwloc=&output=embed"
map_latitude = "17.596298100645598" 
# 17.596298100645598, 78.1232546786667
map_longitude = "78.1232546786667"
map_marker = "images/marker.png"
# cookies
[params.cookies]
enable = false
expire_days = 2

# social site

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/ADITYAK83481478"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/in/aditya-singh-9639a8175/"

[[params.social]]
icon = "ti-github"
URL = "https://github.com/rodosingh"

[[params.email_icon]]
icon = "ti-github"
URL = "https://github.com/rodosingh"

[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/RodoAditya/"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/rodosingh/"

[[params.social]]
icon = "ti-music"
URL = "https://open.spotify.com/user/312ybkhvukb4xot5q675x2kwkp6m"
